/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <android/bitmap.h>
#include <stdio.h>
#include <stdlib.h>
/* Header for class com_hwanee_engine_ColorEngine */

#ifndef _Included_com_hwanee_engine_ColorEngine
#define _Included_com_hwanee_engine_ColorEngine
#ifdef __cplusplus
extern "C" {
#endif

    char getHexValue(int value) {
    __android_log_print(ANDROID_LOG_INFO, "color", "getHexValue #1 = %d", value);
	if (value < 0)
		return -1;
	if (value > 16)
		return -1;
	//if (value <= 9) return (char)value;
	if (value <= 9)
		return '0' + value;
	value -= 10;
	return (char) ('A' + value);
}

    void IntegerToHexadecimal(int value, char *hexString, int* size) {
    __android_log_print(ANDROID_LOG_INFO, "color", "IntegerToHexadecimal #1 = %d", value);
	int i = 0;
	int remainders[2] = {0,0};
	int result = value;
	while (result) {
		remainders[i++] = result % 16;
		result /= (int) 16;
	}
	int j = 0;
        for (i = 0; i < 2; i++) {
    __android_log_print(ANDROID_LOG_INFO, "color", "IntegerToHexadecimal %d = %d", i, remainders[i]);
		char c = getHexValue(remainders[i]);
	 __android_log_print(ANDROID_LOG_INFO, "color", "IntegerToHexadecimal char c =  = %c", c);
		*(hexString + ((*size)++)) = c;
	}
    __android_log_print(ANDROID_LOG_INFO, "color", "%s", hexString);
}

/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertColorCodeToRGB
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hwanee_engine_ColorEngine_convertColorCodeToRGB(JNIEnv * env, jclass _class, jstring colorcode);

/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertRGBToColorCode
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hwanee_engine_ColorEngine_convertRGBToColorCode(JNIEnv * env, jclass _class, jintArray rgb) {
   int size = 0;
	__android_log_print(ANDROID_LOG_INFO, "color", "convertRGBToColorCode #1");
	char* hexString = (char*) malloc(6);
    __android_log_print(ANDROID_LOG_INFO, "color", "convertRGBToColorCode #2");
    int* rgbdata = (*env)->GetIntArrayElements(env, rgb, NULL);
    __android_log_print(ANDROID_LOG_INFO, "color", "%d %d %d", rgbdata[0], rgbdata[1], rgbdata[2]);
    __android_log_print(ANDROID_LOG_INFO, "color", "convertRGBToColorCode #3");
	int i = 0;
	for (i = 0; i < 3; i++) {
    __android_log_print(ANDROID_LOG_INFO, "color", "convertRGBToColorCode #4 size = %d", size);
		IntegerToHexadecimal(rgbdata[i], hexString, &size);
	}
    __android_log_print(ANDROID_LOG_INFO, "color", "%s",  hexString);
    __android_log_print(ANDROID_LOG_INFO, "color", "convertRGBToColorCode #5");
	return (*env)->NewStringUTF(env, hexString);
}

#ifdef __cplusplus
}
#endif
#endif
