/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <android/bitmap.h>
#include <stdio.h>
#include <stdlib.h>
/* Header for class com_hwanee_engine_ColorEngine */

#ifndef _Included_com_hwanee_engine_ColorEngine
#define _Included_com_hwanee_engine_ColorEngine
#ifdef __cplusplus
extern "C" {
#endif

char getHexValue(int value) {
	if (value < 0)
		return -1;
	if (value > 16)
		return -1;
	//if (value <= 9) return (char)value;
	if (value <= 9)
		return '0' + value;
	value -= 10;
	return (char) ('A' + value);
}
    
void HexadecimalToInterger(char* colorhex, int* rgb){
    int i=0;
    int j=0;
    for(i=0; i<6; i += 2) {
    char* tmp = (char*)malloc(sizeof(char)*2);
    memcpy(tmp, colorhex+i, sizeof(char)*2);
    *(rgb+j) = (int)strtol(tmp, NULL,16);
        j++;
    }
}

void IntegerToHexadecimal(int value, char *hexString, int* size) {
    int i = 0;
    int remainders[2] = {0,0};
    int result = value;
    remainders[0] = result / 16;
    remainders[1] = result % 16;
    
    int j = 0;
    for (j =0; j < 2; j++) {
        char c = getHexValue(remainders[j]);
        *(hexString + (*size)++) = c;
    }
}
/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertColorCodeToRGB
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hwanee_engine_ColorEngine_convertColorCodeToRGB(JNIEnv * env, jclass _class, jstring colorcode){
    char* colorhex = (*env)->GetStringUTFChars(env, colorcode, 0);
    int* rgb = (int*) malloc(3);
    HexadecimalToInterger(colorhex, rgb);
    (*env)->ReleaseStringUTFChars(env, colorcode, colorhex);
    jintArray newRgb = (*env)->NewIntArray(env, 3);
    jint *narr = (*env)->GetIntArrayElements(env, newRgb, 0);
    int i = 0;
    for(i=0; i<3; i++){
        narr[i] = rgb[i];
    }
    //(*env)->ReleaseIntArrayElements(env, narr,newRgb,0);
    return newRgb;
}

/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertRGBToColorCode
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hwanee_engine_ColorEngine_convertRGBToColorCode(JNIEnv * env, jclass _class, jintArray rgb) {
    int size = 0;
    char* hexString = (char*) malloc(6);
    int* rgbdata = (*env)->GetIntArrayElements(env, rgb, NULL);
    int i = 0;
    for (i = 0; i < 3; i++) {
        IntegerToHexadecimal(rgbdata[i], hexString, &size);
    }
    (*env)->ReleaseIntArrayElements(env, rgb, rgbdata, NULL);
    // free(hexString);
    return (*env)->NewStringUTF(env, hexString);
}

#ifdef __cplusplus
}
#endif
#endif
