/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hwanee_engine_ColorEngine */

#ifndef _Included_com_hwanee_engine_ColorEngine
#define _Included_com_hwanee_engine_ColorEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertColorCodeToRGB
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hwanee_engine_ColorEngine_convertColorCodeToRGB
    (JNIEnv * env, jclass _class, jstring colorcode);

/*
 * Class:     com_hwanee_engine_ColorEngine
 * Method:    convertRGBToColorCode
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hwanee_engine_ColorEngine_convertRGBToColorCode
    (JNIEnv * env, jclass _class, jintArray rgb);

#ifdef __cplusplus
}
#endif
#endif
